// Maps driver surnames to their 8-bit portrait filenames
const driverPhotoMap = {
    'Hamilton': 'lewis_hamilton_8bit.png',
    'Schumacher': 'michael_schumacher_8bit.png',
    'Verstappen': 'max_verstappen_8bit.png',
    'Vettel': 'sebastian_vettel_8bit.png',
    'Prost': 'alain_prost_8bit.png',
    'Senna': 'ayrton_senna_8bit.png',
    'Alonso': 'fernando_alonso_8bit.png',
    'Mansell': 'nigel_mansell_8bit.png',
    'Stewart': 'jackie_stewart_8bit.png',
    'Lauda': 'niki_lauda_8bit.png',
    'Clark': 'jim_clark_8bit.png',
    'Fangio': 'juan_fangio_8bit.png',
    'Piquet': 'nelson_piquet_8bit.png',
    'Rosberg': 'nico_rosberg_8bit.png',
    'Hill': 'damon_hill_8bit.png',
    'G. Hill': 'graham_hill_8bit.png', // Added Graham Hill
    'Graham Hill': 'graham_hill_8bit.png',
    'Räikkönen': 'kimi_raikkonen_8bit.png',
    'Häkkinen': 'mika_hakkinen_8bit.png',
    'Moss': 'stirling_moss_8bit.png',
    'Button': 'jenson_button_8bit.png',
    'Brabham': 'jack_brabham_8bit.png',
    'Fittipaldi': 'emerson_fittipaldi_8bit.png',
    'Ascari': 'alberto_ascari_8bit.png',
    'Coulthard': 'david_coulthard_8bit.png',
    'Andretti': 'mario_andretti_8bit.png',
    'Jones': 'alan_jones_8bit.png',
    'Reutemann': 'carlos_reutemann_8bit.png',
    'Barrichello': 'rubens_barrichello_8bit.png',
    'Massa': 'felipe_massa_8bit.png',
    'Villeneuve': 'jacques_villeneuve_8bit.png',
    'Berger': 'gerhard_berger_8bit.png',
    'Bottas': 'valtteri_bottas_8bit.png',
    'Hunt': 'james_hunt_8bit.png',
    'Peterson': 'ronnie_peterson_8bit.png',
    'Leclerc': 'charles_leclerc_8bit.png',
    'Ricciardo': 'daniel_ricciardo_8bit.png',
    'Norris': 'lando_norris_8bit.png',
    'Sainz': 'carlos_sainz_8bit.png',
    'Russell': 'george_russell_8bit.png',
    // New additions
    'Webber': 'mark_webber_8bit.png',
    'Kubica': 'robert_kubica_8bit.png',
    'Pérez': 'sergio_perez_8bit.png',
    'Perez': 'sergio_perez_8bit.png',
    'Piastri': 'oscar_piastri_8bit.png',
    'Albon': 'alex_albon_8bit.png',
    'Stroll': 'lance_stroll_8bit.png',
    'Tsunoda': 'yuki_tsunoda_8bit.png',
    'Gasly': 'pierre_gasly_8bit.png',
    'Ocon': 'esteban_ocon_8bit.png',
    'Zhou': 'zhou_guanyu_8bit.png',
    'Magnussen': 'kevin_magnussen_8bit.png',
    'Hülkenberg': 'nico_hulkenberg_8bit.png',
    'Hulkenberg': 'nico_hulkenberg_8bit.png',
    'Nakajima': 'kazuki_nakajima_8bit.png',
    'Heidfeld': 'nick_heidfeld_8bit.png',
    'Kovalainen': 'heikki_kovalainen_8bit.png',
    // Generated Legends & Rookies
    'Scheckter': 'jody_scheckter_8bit.png',
    'Hawthorn': 'mike_hawthorn_8bit.png',
    'P. Hill': 'phil_hill_8bit.png',
    'Phil Hill': 'phil_hill_8bit.png',
    'K. Rosberg': 'keke_rosberg_8bit.png',
    'Keke Rosberg': 'keke_rosberg_8bit.png',
    'G. Villeneuve': 'gilles_villeneuve_8bit.png',
    'Gilles Villeneuve': 'gilles_villeneuve_8bit.png',
    'Sargeant': 'logan_sargeant_8bit.png',
    'Lawson': 'liam_lawson_8bit.png',
    'Antonelli': 'kimi_antonelli_8bit.png',
    // Mass Batch (Champs & Stars)
    'Farina': 'nino_farina_8bit.png',
    'Surtees': 'john_surtees_8bit.png',
    'Hulme': 'denny_hulme_8bit.png',
    'Rindt': 'jochen_rindt_8bit.png',
    'Ickx': 'jacky_ickx_8bit.png',
    'Regazzoni': 'clay_regazzoni_8bit.png',
    'Montoya': 'juan_pablo_montoya_8bit.png',
    'R. Schumacher': 'ralf_schumacher_8bit.png',
    'Ralf Schumacher': 'ralf_schumacher_8bit.png',
    'Alesi': 'jean_alesi_8bit.png',
    // Final Batch (Before Limit)
    'McLaren': 'bruce_mclaren_8bit.png',
    'Gurney': 'dan_gurney_8bit.png',
    'Cevert': 'francois_cevert_8bit.png',
    'Patrese': 'riccardo_patrese_8bit.png',
    // New Batch (Validation)
    'Arnoux': 'rene_arnoux_8bit.png',
    'Laffite': 'jacques_laffite_8bit.png',
    'Brooks': 'tony_brooks_8bit.png',
    'Alboreto': 'michele_alboreto_8bit.png',
    'Watson': 'john_watson_8bit.png',
    'Irvine': 'eddie_irvine_8bit.png',
    'Fisichella': 'giancarlo_fisichella_8bit.png',
    'Frentzen': 'heinz_harald_frentzen_8bit.png',
    // Batch 2 & 3 & 4 additions
    'Trulli': 'jarno_trulli_8bit.png',
    'Panis': 'olivier_panis_8bit.png',
    'Herbert': 'johnny_herbert_8bit.png',
    'Brundle': 'martin_brundle_8bit.png',
    'Salo': 'mika_salo_8bit.png',
    'Jos Verstappen': 'jos_verstappen_8bit.png',
    'de la Rosa': 'pedro_de_la_rosa_8bit.png',
    'Sato': 'takuma_sato_8bit.png',
    'Kobayashi': 'kamui_kobayashi_8bit.png',
    'Grosjean': 'romain_grosjean_8bit.png',
    'Depailler': 'patrick_depailler_8bit.png',
    'Pironi': 'didier_pironi_8bit.png',
    'de Angelis': 'elio_de_angelis_8bit.png',
    'Collins': 'peter_collins_8bit.png',
    'von Trips': 'wolfgang_von_trips_8bit.png',
    'Siffert': 'jo_siffert_8bit.png',
    'Rodriguez': 'pedro_rodriguez_8bit.png',
    'Rodríguez': 'pedro_rodriguez_8bit.png', // Handle accent
    'Pedro Rodriguez': 'pedro_rodriguez_8bit.png',
    'Bandini': 'lorenzo_bandini_8bit.png',
    // Recent Batch Additions
    'Boutsen': 'thierry_boutsen_8bit.png',
    'González': 'jose_froilan_gonzalez_8bit.png',
    'Gonzalez': 'jose_froilan_gonzalez_8bit.png',
    'Jabouille': 'jean_pierre_jabouille_8bit.png',
    'Revson': 'peter_revson_8bit.png',
    'Tambay': 'patrick_tambay_8bit.png',
    'Trintignant': 'maurice_trintignant_8bit.png',
    'Vukovich': 'bill_vukovich_8bit.png',
    'Alesi': 'jean_alesi_8bit.png',
    'Baghetti': 'giancarlo_baghetti_8bit.png',
    'Bandini': 'lorenzo_bandini_8bit.png',
    'Beltoise': 'jean_pierre_beltoise_8bit.png',
    'Bonnier': 'jo_bonnier_8bit.png',
    'Brambilla': 'vittorio_brambilla_8bit.png',
    'Bryan': 'jimmy_bryan_8bit.png',
    'Cevert': 'francois_cevert_8bit.png',
    'Fagioli': 'luigi_fagioli_8bit.png',
    'Flaherty': 'pat_flaherty_8bit.png',
    'Gasly': 'pierre_gasly_8bit.png',
    'Gethin': 'peter_gethin_8bit.png',
    'Ginther': 'richie_ginther_8bit.png',
    'Hanks': 'sam_hanks_8bit.png',
    'Ireland': 'innes_ireland_8bit.png',
    'Kovalainen': 'heikki_kovalainen_8bit.png',
    'Kubica': 'robert_kubica_8bit.png',
    'Maldonado': 'pastor_maldonado_8bit.png',
    'Mass': 'jochen_mass_8bit.png',
    'Musso': 'luigi_musso_8bit.png',
    'alessandro-nannini': '/assets/alessandro_nannini_8bit.png',
    'gunnar-nilsson': '/assets/gunnar_nilsson_8bit.png',
    'esteban-ocon': '/assets/esteban_ocon_8bit.png',
    'carlos-pace': '/assets/carlos_pace_8bit.png',
    'olivier-panis': '/assets/olivier_panis_8bit.png',
    'johnnie-parsons': '/assets/johnnie_parsons_8bit.png',
    'jim-rathmann': '/assets/jim_rathmann_8bit.png',
    'troy-ruttman': '/assets/troy_ruttman_8bit.png',
    'ludovico-scarfiotti': '/assets/ludovico_scarfiotti_8bit.png',
    'bob-sweikert': '/assets/bob_sweikert_8bit.png',
    'piero-taruffi': '/assets/piero_taruffi_8bit.png',
    'jarno-trulli': '/assets/jarno_trulli_8bit.png',
    'lee-wallard': '/assets/lee_wallard_8bit.png',
    'rodger-ward': '/assets/rodger_ward_8bit.png',
    'carlo-abate': '/assets/carlo_abate_8bit.png',
    'george-abecassis': '/assets/george_abecassis_8bit.png',
    'kenny-acheson': '/assets/kenny_acheson_8bit.png',
    'philippe-adams': '/assets/philippe_adams_8bit.png',
    'walt-ader': '/assets/walt_ader_8bit.png',
    'kurt-adolff': '/assets/kurt_adolff_8bit.png',
    'fred-agabashian': '/assets/fred_agabashian_8bit.png',
    'kurt-ahrens': '/assets/kurt_ahrens_8bit.png',
    'jack-aitken': '/assets/jack_aitken_8bit.png',
    'christijan-albers': '/assets/christijan_albers_8bit.png',
    'alexander-albon': '/assets/alexander_albon_8bit.png',
    'jaime-alguersuari': '/assets/jaime_alguersuari_8bit.png',
    'philippe-alliot': '/assets/philippe_alliot_8bit.png',
    'cliff-allison': '/assets/cliff_allison_8bit.png',
    'giovanna-amati': '/assets/giovanna_amati_8bit.png',
    'red-amick': '/assets/red_amick_8bit.png',
    'george-amick': '/assets/george_amick_8bit.png',
    'chris-amon': '/assets/chris_amon_8bit.png',
    'bob-anderson': '/assets/bob_anderson_8bit.png',
    'conny-andersson': '/assets/conny_andersson_8bit.png',
    'michael-andretti': '/assets/michael_andretti_8bit.png',
    'keith-andrews': '/assets/keith_andrews_8bit.png',
    'marco-apicella': '/assets/marco_apicella_8bit.png',
    'frank-armi': '/assets/frank_armi_8bit.png',
    'chuck-arnold': '/assets/chuck_arnold_8bit.png',
    'peter-arundell': '/assets/peter_arundell_8bit.png',
    'peter-ashdown': '/assets/peter_ashdown_8bit.png',
    'ian-ashley': '/assets/ian_ashley_8bit.png',
    'gerry-ashmore': '/assets/gerry_ashmore_8bit.png',
    'bill-aston': '/assets/bill_aston_8bit.png',
    'richard-attwood': '/assets/richard_attwood_8bit.png',
    'manny-ayulo': '/assets/manny_ayulo_8bit.png',
    'luca-badoer': '/assets/luca_badoer_8bit.png',
    'julian-bailey': '/assets/julian_bailey_8bit.png',
    'mauro-baldi': '/assets/mauro_baldi_8bit.png',
    'bobby-ball': '/assets/bobby_ball_8bit.png',
    'marcel-balsa': '/assets/marcel_balsa_8bit.png',
    'henry-banks': '/assets/henry_banks_8bit.png',
    'fabrizio-barbazza': '/assets/fabrizio_barbazza_8bit.png',
    'john-barber': '/assets/john_barber_8bit.png',
    'skip-barber': '/assets/skip_barber_8bit.png',
    'paolo-barilla': '/assets/paolo_barilla_8bit.png',
    'michael-bartels': '/assets/michael_bartels_8bit.png',
    'edgar-barth': '/assets/edgar_barth_8bit.png',
    'giorgio-bassi': '/assets/giorgio_bassi_8bit.png',
    'erwin-bauer': '/assets/erwin_bauer_8bit.png',
    'zsolt-baumgartner': '/assets/zsolt_baumgartner_8bit.png',
    'elie-bayol': '/assets/elie_bayol_8bit.png',
    'oliver-bearman': '/assets/oliver_bearman_8bit.png',
    'don-beauman': '/assets/don_beauman_8bit.png',
    'gunther-bechem': '/assets/gunther_bechem_8bit.png',
    'jean-behra': '/assets/jean_behra_8bit.png',
    'derek-bell': '/assets/derek_bell_8bit.png',
    'stefan-bellof': '/assets/stefan_bellof_8bit.png',
    'paul-belmondo': '/assets/paul_belmondo_8bit.png',
    'tom-belso': '/assets/tom_belso_8bit.png',
    'olivier-beretta': '/assets/olivier_beretta_8bit.png',
    'allen-berg': '/assets/allen_berg_8bit.png',
    'georges-berger': '/assets/georges_berger_8bit.png',
    'eric-bernard': '/assets/eric_bernard_8bit.png',
    'enrique-bernoldi': '/assets/enrique_bernoldi_8bit.png',
    'enrico-bertaggia': '/assets/enrico_bertaggia_8bit.png',
    'tony-bettenhausen': '/assets/tony_bettenhausen_8bit.png',
    'mike-beuttler': '/assets/mike_beuttler_8bit.png',
    'lucien-bianchi': '/assets/lucien_bianchi_8bit.png',
    'jules-bianchi': '/assets/jules_bianchi_8bit.png',
    'gino-bianco': '/assets/gino_bianco_8bit.png',
    'hans-binder': '/assets/hans_binder_8bit.png',
    'clemente-biondetti': '/assets/clemente_biondetti_8bit.png',
    'prince-bira': '/assets/prince_bira_8bit.png',
    // Batch 20
    'Birger': 'pablo_birger_8bit.png',
    'Bisch': 'art_bisch_8bit.png',
    'Blanchard': 'harry_blanchard_8bit.png',
    'Bleekemolen': 'michael_bleekemolen_8bit.png',
    'Blignaut': 'alex_blignaut_8bit.png',
    'Blokdyk': 'trevor_blokdyk_8bit.png',
    'Blundell': 'mark_blundell_8bit.png',
    'Boesel': 'raul_boesel_8bit.png',
    // Batch 21
    'Boffa': 'menato_boffa_8bit.png',
    'Bondurant': 'bob_bondurant_8bit.png',
    'Bonetto': 'felice_bonetto_8bit.png',
    'Bonomi': 'roberto_bonomi_8bit.png',
    'Bordeu': 'juan_manuel_bordeu_8bit.png',
    'Borgudd': 'slim_borgudd_8bit.png',
    'Botha': 'luki_botha_8bit.png',
    'Boullion': 'jean_christophe_boullion_8bit.png',
    // Batch 22
    'Bourdais': 'sebastien_bourdais_8bit.png',
    'Boyd': 'johnny_boyd_8bit.png',
    'David Brabham': 'david_brabham_8bit.png',
    'Gary Brabham': 'gary_brabham_8bit.png',
    'Brack': 'bill_brack_8bit.png',
    'Brambilla': 'ernesto_brambilla_8bit.png',
    'Branca': 'toni_branca_8bit.png',
    'Branca': 'toni_branca_8bit.png',
    'Brancatelli': 'gianfranco_brancatelli_8bit.png',
    // Batch 23 (Partial)
    'Brandon': 'eric_brandon_8bit.png',
    'Branson': 'don_branson_8bit.png',
    'Bridger': 'tom_bridger_8bit.png',
    'Brise': 'tony_brise_8bit.png',
    'Bristow': 'chris_bristow_8bit.png',
    'Broeker': 'peter_broeker_8bit.png',
    'Warwick Brown': 'warwick_brown_8bit.png',
    'Walt Brown': 'walt_brown_8bit.png',
    // Batch 24
    'Alan Brown': 'alan_brown_8bit.png',
    'Brudes': 'adolf_brudes_8bit.png',
    'Brundle': 'martin_brundle_8bit.png',
    'Bruni': 'gianmaria_bruni_8bit.png',
    'Bucci': 'clemar_bucci_8bit.png',
    'Bucknum': 'ronnie_bucknum_8bit.png',
    'Bueb': 'ivor_bueb_8bit.png',
    'Buemi': 'sebastien_buemi_8bit.png',
    // Batch 25
    'Bueno': 'luiz_bueno_8bit.png',
    'Burgess': 'ian_burgess_8bit.png',
    'Burti': 'luciano_burti_8bit.png',
    'Bussinello': 'roberto_bussinello_8bit.png',
    'Byrne': 'tommy_byrne_8bit.png',
    'Cabantous': 'yves_cabantous_8bit.png',
    'Cabianca': 'giulio_cabianca_8bit.png',
    'Cabral': 'mario_de_araujo_cabral_8bit.png',
    // Batch 26
    'Cade': 'phil_cade_8bit.png',
    'Caffi': 'alex_caffi_8bit.png',
    'Campbell-Jones': 'john_campbell_jones_8bit.png',
    'Campos': 'adrian_campos_8bit.png',
    'Cannon': 'john_cannon_8bit.png',
    'Cantoni': 'eitel_cantoni_8bit.png',
    'Cantrell': 'bill_cantrell_8bit.png',
    'Capelli': 'ivan_capelli_8bit.png',
    // Batch 27
    'Carini': 'piero_carini_8bit.png',
    'Carter': 'duane_carter_8bit.png',
    'Castellotti': 'eugenio_castellotti_8bit.png',
    'Cecotto': 'johnny_cecotto_8bit.png',
    'Chaboud': 'eugene_chaboud_8bit.png',
    'Chamberlain': 'jay_chamberlain_8bit.png',
    'Chandhok': 'karun_chandhok_8bit.png',
    'Chapman': 'colin_chapman_8bit.png',
    // Batch 28
    'Charlton': 'dave_charlton_8bit.png',
    'Chaves': 'pedro_chaves_8bit.png',
    'Cheesbourg': 'bill_cheesbourg_8bit.png',
    'Cheever': 'eddie_cheever_8bit.png',
    'Chiesa': 'andrea_chiesa_8bit.png',
    'Chilton': 'max_chilton_8bit.png',
    'Chimeri': 'ettore_chimeri_8bit.png',
    'Chiron': 'louis_chiron_8bit.png',
    // Batch 29
    'Chitwood': 'joie_chitwood_8bit.png',
    'Christie': 'bob_christie_8bit.png',
    'Claes': 'johnny_claes_8bit.png',
    'Clapham': 'david_clapham_8bit.png',
    'Cogan': 'kevin_cogan_8bit.png',
    'Colapinto': 'franco_colapinto_8bit.png',
    'Collomb': 'bernard_collomb_8bit.png',
    'Colombo': 'alberto_colombo_8bit.png',
    // Batch 30
    'Comas': 'erik_comas_8bit.png',
    'Comotti': 'franco_comotti_8bit.png',
    'Connor': 'george_connor_8bit.png',
    'Constantine': 'george_constantine_8bit.png',
    'Cordts': 'john_cordts_8bit.png',
    'Courage': 'piers_courage_8bit.png',
    'Craft': 'chris_craft_8bit.png',
    'Crawford': 'jim_crawford_8bit.png',
    // Batch 31
    'Ray Crawford': 'ray_crawford_8bit.png',
    'Crespo': 'alberto_crespo_8bit.png',
    'Creus': 'antonio_creus_8bit.png',
    'Crockett': 'larry_crockett_8bit.png',
    'Crook': 'tony_crook_8bit.png',
    'Cross': 'art_cross_8bit.png',
    'Crossley': 'geoff_crossley_8bit.png',
    'Cruz': 'adolfo_cruz_8bit.png',
    // Batch 32
    'Daigh': 'chuck_daigh_8bit.png',
    'Dalmas': 'yannick_dalmas_8bit.png',
    'Daly': 'derek_daly_8bit.png',
    'da Matta': 'cristiano_da_matta_8bit.png',
    "d'Ambrosio": 'jerome_dambrosio_8bit.png',
    'Danner': 'christian_danner_8bit.png',
    'Daponte': 'jorge_daponte_8bit.png',
    'da Silva Ramos': 'hernando_da_silva_ramos_8bit.png',
    // Batch 33
    'Davidson': 'anthony_davidson_8bit.png',
    'Davies': 'jimmy_davies_8bit.png',
    'Davis': 'colin_davis_8bit.png',
    'Daywalt': 'jimmy_daywalt_8bit.png',
    'de Adamich': 'andrea_de_adamich_8bit.png',
    'de Beaufort': 'carel_godin_de_beaufort_8bit.png',
    'de Cesaris': 'andrea_de_cesaris_8bit.png',
    'de Changy': 'alain_de_changy_8bit.png',
    // Batch 34
    'de Dryver': 'bernard_de_dryver_8bit.png',
    'de Filippis': 'maria_de_filippis_8bit.png',
    'de Graffenried': 'toulo_de_graffenried_8bit.png',
    'de Klerk': 'peter_de_klerk_8bit.png',
    'de la Rosa': 'pedro_de_la_rosa_8bit.png',
    'Délétraz': 'jean_denis_deletraz_8bit.png',
    'de Portago': 'alfonso_de_portago_8bit.png',
    'de Riu': 'giovanni_de_riu_8bit.png',
    // Batch 35
    'de Terra': 'max_de_terra_8bit.png',
    'de Tomaso': 'alessandro_de_tomaso_8bit.png',
    'de Tornaco': 'charles_de_tornaco_8bit.png',
    'de Villota': 'emilio_de_villota_8bit.png',
    'de Vos': 'ernie_de_vos_8bit.png',
    'de Vries': 'nyck_de_vries_8bit.png',
    'di Grassi': 'lucas_di_grassi_8bit.png',
    'Diniz': 'pedro_diniz_8bit.png',
    // Batch 36
    'Dinsmore': 'duke_dinsmore_8bit.png',
    'di Resta': 'paul_di_resta_8bit.png',
    'Dochnal': 'frank_dochnal_8bit.png',
    'Dolhem': 'jose_dolhem_8bit.png',
    'Donnelly': 'martin_donnelly_8bit.png',
    'Donohue': 'mark_donohue_8bit.png',
    'Doohan': 'jack_doohan_8bit.png',
    'Doornbos': 'robert_doornbos_8bit.png',
    // Batch 37
    "d'Orey": 'fritz_d_orey_8bit.png',
    'Downing': 'ken_downing_8bit.png',
    'Drake': 'bob_drake_8bit.png',
    'Driver': 'paddy_driver_8bit.png',
    'Drogo': 'piero_drogo_8bit.png',
    'Duke': 'geoff_duke_8bit.png',
    'Dumfries': 'johnny_dumfries_8bit.png',
    'Duncan': 'len_duncan_8bit.png',
    // Batch 38 (Partial)
    'Dusio': 'piero_dusio_8bit.png',
    'Eaton': 'george_eaton_8bit.png',
    'Ecclestone': 'bernie_ecclestone_8bit.png',
    'Edmunds': 'don_edmunds_8bit.png',
    'Edwards': 'guy_edwards_8bit.png',
    'Elford': 'vic_elford_8bit.png',
    'Elisian': 'ed_elisian_8bit.png',
    'Emery': 'paul_emery_8bit.png',
    // Batch 39
    'Enge': 'tomas_enge_8bit.png',
    'England': 'paul_england_8bit.png',
    'Ericsson': 'marcus_ericsson_8bit.png',
    'Ertl': 'harald_ertl_8bit.png',
    'Estéfano': 'nasif_estefano_8bit.png',
    'Étancelin': 'philippe_etancelin_8bit.png',
    'Evans': 'bob_evans_8bit.png',
    'T. Fabi': 'teo_fabi_8bit.png',
    // Batch 40 (Partial)
    'C. Fabi': 'corrado_fabi_8bit.png',
    'Fabre': 'pascal_fabre_8bit.png',
    'Facetti': 'carlo_facetti_8bit.png',
};

export function getDriverPhoto(surname, forename) {
    // Check for full name match first (e.g. "Jos Verstappen")
    if (forename) {
        const fullName = `${forename} ${surname}`;
        // Try exact full name
        if (driverPhotoMap[fullName]) {
            return `/assets/${driverPhotoMap[fullName]}`;
        }
        // Try simple concatenation just in case (e.g. "Graham Hill" is in map, but passed as separate)
    }

    const filename = driverPhotoMap[surname];
    if (filename) {
        return `/assets/${filename}`;
    }
    return null;
}

export function getDriverPhotoOrPlaceholder(forename, surname) {
    const photo = getDriverPhoto(surname, forename);
    if (photo) return photo;
    // Fallback to UI Avatars
    return `https://ui-avatars.com/api/?name=${forename}+${surname}&background=E10600&color=fff&size=128`;
}

export default driverPhotoMap;
