// Maps driver surnames to their 8-bit portrait filenames
const driverPhotoMap = {
    'Hamilton': 'lewis_hamilton_8bit.png',
    'Schumacher': 'michael_schumacher_8bit.png',
    'Verstappen': 'max_verstappen_8bit.png',
    'Vettel': 'sebastian_vettel_8bit.png',
    'Prost': 'alain_prost_8bit.png',
    'Senna': 'ayrton_senna_8bit.png',
    'Alonso': 'fernando_alonso_8bit.png',
    'Mansell': 'nigel_mansell_8bit.png',
    'Stewart': 'jackie_stewart_8bit.png',
    'Lauda': 'niki_lauda_8bit.png',
    'Clark': 'jim_clark_8bit.png',
    'Fangio': 'juan_fangio_8bit.png',
    'Piquet': 'nelson_piquet_8bit.png',
    'Rosberg': 'nico_rosberg_8bit.png',
    'Hill': 'damon_hill_8bit.png',
    'G. Hill': 'graham_hill_8bit.png', // Added Graham Hill
    'Graham Hill': 'graham_hill_8bit.png',
    'Räikkönen': 'kimi_raikkonen_8bit.png',
    'Häkkinen': 'mika_hakkinen_8bit.png',
    'Moss': 'stirling_moss_8bit.png',
    'Button': 'jenson_button_8bit.png',
    'Brabham': 'jack_brabham_8bit.png',
    'Fittipaldi': 'emerson_fittipaldi_8bit.png',
    'Ascari': 'alberto_ascari_8bit.png',
    'Coulthard': 'david_coulthard_8bit.png',
    'Andretti': 'mario_andretti_8bit.png',
    'Jones': 'alan_jones_8bit.png',
    'Reutemann': 'carlos_reutemann_8bit.png',
    'Barrichello': 'rubens_barrichello_8bit.png',
    'Massa': 'felipe_massa_8bit.png',
    'Villeneuve': 'jacques_villeneuve_8bit.png',
    'Berger': 'gerhard_berger_8bit.png',
    'Bottas': 'valtteri_bottas_8bit.png',
    'Hunt': 'james_hunt_8bit.png',
    'Peterson': 'ronnie_peterson_8bit.png',
    'Leclerc': 'charles_leclerc_8bit.png',
    'Ricciardo': 'daniel_ricciardo_8bit.png',
    'Norris': 'lando_norris_8bit.png',
    'Sainz': 'carlos_sainz_8bit.png',
    'Russell': 'george_russell_8bit.png',
    // New additions
    'Webber': 'mark_webber_8bit.png',
    'Kubica': 'robert_kubica_8bit.png',
    'Pérez': 'sergio_perez_8bit.png',
    'Perez': 'sergio_perez_8bit.png',
    'Piastri': 'oscar_piastri_8bit.png',
    'Albon': 'alex_albon_8bit.png',
    'Stroll': 'lance_stroll_8bit.png',
    'Tsunoda': 'yuki_tsunoda_8bit.png',
    'Gasly': 'pierre_gasly_8bit.png',
    'Ocon': 'esteban_ocon_8bit.png',
    'Zhou': 'zhou_guanyu_8bit.png',
    'Magnussen': 'kevin_magnussen_8bit.png',
    'Hülkenberg': 'nico_hulkenberg_8bit.png',
    'Hulkenberg': 'nico_hulkenberg_8bit.png',
    'Nakajima': 'kazuki_nakajima_8bit.png',
    'Heidfeld': 'nick_heidfeld_8bit.png',
    'Kovalainen': 'heikki_kovalainen_8bit.png',
    // Generated Legends & Rookies
    'Scheckter': 'jody_scheckter_8bit.png',
    'Hawthorn': 'mike_hawthorn_8bit.png',
    'P. Hill': 'phil_hill_8bit.png',
    'Phil Hill': 'phil_hill_8bit.png',
    'K. Rosberg': 'keke_rosberg_8bit.png',
    'Keke Rosberg': 'keke_rosberg_8bit.png',
    'G. Villeneuve': 'gilles_villeneuve_8bit.png',
    'Gilles Villeneuve': 'gilles_villeneuve_8bit.png',
    'Sargeant': 'logan_sargeant_8bit.png',
    'Lawson': 'liam_lawson_8bit.png',
    'Antonelli': 'kimi_antonelli_8bit.png',
    // Mass Batch (Champs & Stars)
    'Farina': 'nino_farina_8bit.png',
    'Surtees': 'john_surtees_8bit.png',
    'Hulme': 'denny_hulme_8bit.png',
    'Rindt': 'jochen_rindt_8bit.png',
    'Ickx': 'jacky_ickx_8bit.png',
    'Regazzoni': 'clay_regazzoni_8bit.png',
    'Montoya': 'juan_pablo_montoya_8bit.png',
    'R. Schumacher': 'ralf_schumacher_8bit.png',
    'Ralf Schumacher': 'ralf_schumacher_8bit.png',
    'Alesi': 'jean_alesi_8bit.png',
    // Final Batch (Before Limit)
    'McLaren': 'bruce_mclaren_8bit.png',
    'Gurney': 'dan_gurney_8bit.png',
    'Cevert': 'francois_cevert_8bit.png',
    'Patrese': 'riccardo_patrese_8bit.png',
    // New Batch (Validation)
    'Arnoux': 'rene_arnoux_8bit.png',
    'Laffite': 'jacques_laffite_8bit.png',
    'Brooks': 'tony_brooks_8bit.png',
    'Alboreto': 'michele_alboreto_8bit.png',
    'Watson': 'john_watson_8bit.png',
    'Irvine': 'eddie_irvine_8bit.png',
    'Fisichella': 'giancarlo_fisichella_8bit.png',
    'Frentzen': 'heinz_harald_frentzen_8bit.png',
    // Batch 2 & 3 & 4 additions
    'Trulli': 'jarno_trulli_8bit.png',
    'Panis': 'olivier_panis_8bit.png',
    'Herbert': 'johnny_herbert_8bit.png',
    'Brundle': 'martin_brundle_8bit.png',
    'Salo': 'mika_salo_8bit.png',
    'Jos Verstappen': 'jos_verstappen_8bit.png',
    'de la Rosa': 'pedro_de_la_rosa_8bit.png',
    'Sato': 'takuma_sato_8bit.png',
    'Kobayashi': 'kamui_kobayashi_8bit.png',
    'Grosjean': 'romain_grosjean_8bit.png',
    'Depailler': 'patrick_depailler_8bit.png',
    'Pironi': 'didier_pironi_8bit.png',
    'de Angelis': 'elio_de_angelis_8bit.png',
    'Collins': 'peter_collins_8bit.png',
    'von Trips': 'wolfgang_von_trips_8bit.png',
    'Siffert': 'jo_siffert_8bit.png',
    'Rodriguez': 'pedro_rodriguez_8bit.png',
    'Rodríguez': 'pedro_rodriguez_8bit.png', // Handle accent
    'Pedro Rodriguez': 'pedro_rodriguez_8bit.png',
    'Bandini': 'lorenzo_bandini_8bit.png',
    // Recent Batch Additions
    'Boutsen': 'thierry_boutsen_8bit.png',
    'González': 'jose_froilan_gonzalez_8bit.png',
    'Gonzalez': 'jose_froilan_gonzalez_8bit.png',
    'Jabouille': 'jean_pierre_jabouille_8bit.png',
    'Revson': 'peter_revson_8bit.png',
    'Tambay': 'patrick_tambay_8bit.png',
    'Trintignant': 'maurice_trintignant_8bit.png',
    'Vukovich': 'bill_vukovich_8bit.png',
    'Alesi': 'jean_alesi_8bit.png',
    'Baghetti': 'giancarlo_baghetti_8bit.png',
    'Bandini': 'lorenzo_bandini_8bit.png',
    'Beltoise': 'jean_pierre_beltoise_8bit.png',
    'Bonnier': 'jo_bonnier_8bit.png',
    'Brambilla': 'vittorio_brambilla_8bit.png',
    'Bryan': 'jimmy_bryan_8bit.png',
    'Cevert': 'francois_cevert_8bit.png',
    'Fagioli': 'luigi_fagioli_8bit.png',
    'Flaherty': 'pat_flaherty_8bit.png',
    'Gasly': 'pierre_gasly_8bit.png',
    'Gethin': 'peter_gethin_8bit.png',
    'Ginther': 'richie_ginther_8bit.png',
    'Hanks': 'sam_hanks_8bit.png',
    'Ireland': 'innes_ireland_8bit.png',
    'Kovalainen': 'heikki_kovalainen_8bit.png',
    'Kubica': 'robert_kubica_8bit.png',
    'Maldonado': 'pastor_maldonado_8bit.png',
    'Mass': 'jochen_mass_8bit.png',
    'Musso': 'luigi_musso_8bit.png',
    'alessandro-nannini': '/assets/alessandro_nannini_8bit.png',
    'gunnar-nilsson': '/assets/gunnar_nilsson_8bit.png',
    'esteban-ocon': '/assets/esteban_ocon_8bit.png',
    'carlos-pace': '/assets/carlos_pace_8bit.png',
    'olivier-panis': '/assets/olivier_panis_8bit.png',
    'johnnie-parsons': '/assets/johnnie_parsons_8bit.png',
    'jim-rathmann': '/assets/jim_rathmann_8bit.png',
    'troy-ruttman': '/assets/troy_ruttman_8bit.png',
    'ludovico-scarfiotti': '/assets/ludovico_scarfiotti_8bit.png',
    'bob-sweikert': '/assets/bob_sweikert_8bit.png',
    'piero-taruffi': '/assets/piero_taruffi_8bit.png',
    'jarno-trulli': '/assets/jarno_trulli_8bit.png',
    'lee-wallard': '/assets/lee_wallard_8bit.png',
    'rodger-ward': '/assets/rodger_ward_8bit.png',
    'carlo-abate': '/assets/carlo_abate_8bit.png',
    'george-abecassis': '/assets/george_abecassis_8bit.png',
    'kenny-acheson': '/assets/kenny_acheson_8bit.png',
    'philippe-adams': '/assets/philippe_adams_8bit.png',
    'walt-ader': '/assets/walt_ader_8bit.png',
    'kurt-adolff': '/assets/kurt_adolff_8bit.png',
    'fred-agabashian': '/assets/fred_agabashian_8bit.png',
    'kurt-ahrens': '/assets/kurt_ahrens_8bit.png',
    'jack-aitken': '/assets/jack_aitken_8bit.png',
    'christijan-albers': '/assets/christijan_albers_8bit.png',
    'alexander-albon': '/assets/alexander_albon_8bit.png',
    'jaime-alguersuari': '/assets/jaime_alguersuari_8bit.png',
    'philippe-alliot': '/assets/philippe_alliot_8bit.png',
    'cliff-allison': '/assets/cliff_allison_8bit.png',
    'giovanna-amati': '/assets/giovanna_amati_8bit.png',
    'red-amick': '/assets/red_amick_8bit.png',
    'george-amick': '/assets/george_amick_8bit.png',
    'chris-amon': '/assets/chris_amon_8bit.png',
    'bob-anderson': '/assets/bob_anderson_8bit.png',
    'conny-andersson': '/assets/conny_andersson_8bit.png',
    'michael-andretti': '/assets/michael_andretti_8bit.png',
    'keith-andrews': '/assets/keith_andrews_8bit.png',
    'marco-apicella': '/assets/marco_apicella_8bit.png',
    'frank-armi': '/assets/frank_armi_8bit.png',
    'chuck-arnold': '/assets/chuck_arnold_8bit.png',
    'peter-arundell': '/assets/peter_arundell_8bit.png',
    'peter-ashdown': '/assets/peter_ashdown_8bit.png',
    'ian-ashley': '/assets/ian_ashley_8bit.png',
    'gerry-ashmore': '/assets/gerry_ashmore_8bit.png',
    'bill-aston': '/assets/bill_aston_8bit.png',
    'richard-attwood': '/assets/richard_attwood_8bit.png',
    'manny-ayulo': '/assets/manny_ayulo_8bit.png',
    'luca-badoer': '/assets/luca_badoer_8bit.png',
    'julian-bailey': '/assets/julian_bailey_8bit.png',
    'mauro-baldi': '/assets/mauro_baldi_8bit.png',
    'bobby-ball': '/assets/bobby_ball_8bit.png',
    'marcel-balsa': '/assets/marcel_balsa_8bit.png',
    'henry-banks': '/assets/henry_banks_8bit.png',
    'fabrizio-barbazza': '/assets/fabrizio_barbazza_8bit.png',
    'john-barber': '/assets/john_barber_8bit.png',
    'skip-barber': '/assets/skip_barber_8bit.png',
    'paolo-barilla': '/assets/paolo_barilla_8bit.png',
    'michael-bartels': '/assets/michael_bartels_8bit.png',
    'edgar-barth': '/assets/edgar_barth_8bit.png',
    'giorgio-bassi': '/assets/giorgio_bassi_8bit.png',
    'erwin-bauer': '/assets/erwin_bauer_8bit.png',
    'zsolt-baumgartner': '/assets/zsolt_baumgartner_8bit.png',
    'elie-bayol': '/assets/elie_bayol_8bit.png',
    'oliver-bearman': '/assets/oliver_bearman_8bit.png',
    'don-beauman': '/assets/don_beauman_8bit.png',
    'gunther-bechem': '/assets/gunther_bechem_8bit.png',
    'jean-behra': '/assets/jean_behra_8bit.png',
    'derek-bell': '/assets/derek_bell_8bit.png',
    'stefan-bellof': '/assets/stefan_bellof_8bit.png',
    'paul-belmondo': '/assets/paul_belmondo_8bit.png',
    'tom-belso': '/assets/tom_belso_8bit.png',
    'olivier-beretta': '/assets/olivier_beretta_8bit.png',
    'allen-berg': '/assets/allen_berg_8bit.png',
    'georges-berger': '/assets/georges_berger_8bit.png',
    'eric-bernard': '/assets/eric_bernard_8bit.png',
    'enrique-bernoldi': '/assets/enrique_bernoldi_8bit.png',
    'enrico-bertaggia': '/assets/enrico_bertaggia_8bit.png',
    'tony-bettenhausen': '/assets/tony_bettenhausen_8bit.png',
    'mike-beuttler': '/assets/mike_beuttler_8bit.png',
    'lucien-bianchi': '/assets/lucien_bianchi_8bit.png',
    'jules-bianchi': '/assets/jules_bianchi_8bit.png',
    'gino-bianco': '/assets/gino_bianco_8bit.png',
    'hans-binder': '/assets/hans_binder_8bit.png',
    'clemente-biondetti': '/assets/clemente_biondetti_8bit.png',
    'prince-bira': '/assets/prince_bira_8bit.png',
    // Batch 20
    'Birger': 'pablo_birger_8bit.png',
    'Bisch': 'art_bisch_8bit.png',
    'Blanchard': 'harry_blanchard_8bit.png',
    'Bleekemolen': 'michael_bleekemolen_8bit.png',
    'Blignaut': 'alex_blignaut_8bit.png',
    'Blokdyk': 'trevor_blokdyk_8bit.png',
    'Blundell': 'mark_blundell_8bit.png',
    'Boesel': 'raul_boesel_8bit.png',
    // Batch 21 (Partial)
    'Boffa': 'menato_boffa_8bit.png',
};

export function getDriverPhoto(surname, forename) {
    // Check for full name match first (e.g. "Jos Verstappen")
    if (forename) {
        const fullName = `${forename} ${surname}`;
        // Try exact full name
        if (driverPhotoMap[fullName]) {
            return `/assets/${driverPhotoMap[fullName]}`;
        }
        // Try simple concatenation just in case (e.g. "Graham Hill" is in map, but passed as separate)
    }

    const filename = driverPhotoMap[surname];
    if (filename) {
        return `/assets/${filename}`;
    }
    return null;
}

export function getDriverPhotoOrPlaceholder(forename, surname) {
    const photo = getDriverPhoto(surname, forename);
    if (photo) return photo;
    // Fallback to UI Avatars
    return `https://ui-avatars.com/api/?name=${forename}+${surname}&background=E10600&color=fff&size=128`;
}

export default driverPhotoMap;
